
### POST a new crawler
POST http://{{host}}:9003/crawlers
Content-Type: application/json

{
  "name": "Test Crawler",
  "config": {
    "indexPrefix": "crawler_",
    "startUrls": [
      "https://orf.at/"
    ],
    "filterOptions": {
      "siteExclusionPatterns": [],
      "queryParameterExclusionPatterns": [
      ]
    },
    "requestOptions": {
      "requestTimeout": 1500,
      "retries": 1,
      "headers": [
        {
          "name": "User-Agent",
          "value": "Mozilla/5.0 (compatible"
        }
      ]
    },
    "actions": [
      {
        "indexName": "test_index",
        "pathsToMatch": [
          "orf*"
        ],
        "selectorsToMatch": [
        ],
        "contentTypesToMatch": [
          "HTML"
        ]
      }
    ]
  }
}

### GET all crawlers
GET http://{{host}}:9003/crawlers

###
GET http://{{host}}:9003/crawlers/6a83d210-1b73-4a78-ac94-fae009cbe371/status


### GET a crawler
GET http://{{host}}:9003/crawlers/6f9e5e84-4835-4470-80f0-e87befffeb01

### DELETE a crawler
DELETE http://{{host}}:9003/crawlers/{{crawlerId}}

### PUT a crawler's status
PUT http://{{host}}:9003/crawlers/1c1ffa60-117b-40ea-b926-d8de8d72fd1f/run


### PUT a crawler's status
PUT http://{{host}}:9003/crawlers/6a375870-0116-4945-857a-90c28ac5ca31/pause



