
### POST a new crawler
POST http://{{host}}:9003/crawlers
Content-Type: application/json

{
  "name": "Test Crawler",
  "config": {
    "indexPrefix": "crawler_",
    "startUrls": [
      "https://test.io/"
    ],
    "filterOptions": {
      "siteExclusionPatterns": [],
      "queryParameterExclusionPatterns": [
      ]
    },
    "requestOptions": {
      "requestTimeout": 1500,
      "retries": 1,
      "headers": [
        {
          "name": "User-Agent",
          "value": "Mozilla/5.0 (compatible"
        }
      ]
    },
    "actions": [
      {
        "indexName": "test_index",
        "pathsToMatch": [
          "orf*"
        ],
        "selectorsToMatch": [
        ],
        "contentTypesToMatch": [
          "HTML"
        ]
      }
    ]
  }
}

### GET all crawlers
GET http://{{host}}:9003/crawlers

###
GET http://{{host}}:9003/crawlers/d131a691-d79e-4f2b-b64a-754be6d578ba/status


### GET a crawler
GET http://{{host}}:9003/crawlers/6f9e5e84-4835-4470-80f0-e87befffeb01

### DELETE a crawler
DELETE http://{{host}}:9003/crawlers/{{crawlerId}}

### PUT a crawler's status
PUT http://{{host}}:9003/crawlers/81ac20c7-6fdd-4e76-ab3e-1790381e11a3/run


### PUT a crawler's status
PUT http://{{host}}:9003/crawlers/6a375870-0116-4945-857a-90c28ac5ca31/pause



