
### POST a new crawler
POST http://{{host}}:9003/crawlers
Content-Type: application/json

{
  "id": "ae683f02-7a5c-4a79-9c5c-ab93770c46f5",
  "name": "Test Crawler",
  "status": "CREATED",
  "config": {
    "indexPrefix": "crawler_",
    "schedule": "0 0 0 1 1 ? 2099",
    "startUrls": [
      "https://orf.at/"
    ],
    "siteExclusionPatterns": [
      "https://www.google.com/**"
    ],
    "queryParameterExclusionPatterns": [
      "utm_*"
    ],
    "requestOptions": {
      "proxy": {
        "host": "localhost",
        "port": 8080
      },
      "requestTimeout": 1000,
      "retries": 3,
      "headers": [
        {
          "name": "User-Agent",
          "value": "Mozilla/5.0 (compatible"
        }
      ]
    },
    "robotOptions": {
      "ignoreRobotRules": true,
      "ignoreRobotNoIndex": true,
      "ignoreRobotNoFollowTo": true
    },
    "actions": [
      {
        "indexName": "test_index",
        "pathsToMatch": [
          "https://orf.at/*"
        ],
        "selectorsToMatch": [
          ".products",
          "!.featured"
        ],
        "fileTypesToMatch": [
          "HTML",
          "PDF"
        ]
      }
    ]
  }
}

### GET all crawlers
GET http://{{host}}:9003/crawlers

###
GET http://{{host}}:9003/crawlers/1262daa4-4427-48a9-b033-16d56641bcab/status


### GET a crawler
GET http://{{host}}:9003/crawlers/{{crawlerId}}

### DELETE a crawler
DELETE http://{{host}}:9003/crawlers/{{crawlerId}}

### PUT a crawler's status
PUT http://{{host}}:9003/crawlers/3267acba-4302-4694-95a3-9110c0232c4b/run

### PUT a crawler's status
PUT http://{{host}}:9003/crawlers/1509c6ed-564f-4654-bd8b-27060a7c07e5/pause



