
### POST a new crawler
POST http://{{host}}:9003/crawlers
Content-Type: application/json

{
  "name": "Test Crawler",
  "config": {
    "indexPrefix": "crawler_",
    "startUrls": [
      "https://zamg.at/"
    ],
    "filterOptions": {
      "siteExclusionPatterns": [],
      "queryParameterExclusionPatterns": [
      ]
    },
    "requestOptions": {
      "requestTimeout": 1500,
      "retries": 1,
      "headers": [
        {
          "name": "User-Agent",
          "value": "Mozilla/5.0 (compatible"
        }
      ]
    },
    "actions": [
      {
        "indexName": "test_index",
        "pathsToMatch": [
          "orf*"
        ],
        "selectorsToMatch": [
        ],
        "contentTypesToMatch": [
          "HTML"
        ]
      }
    ]
  }
}

### GET all crawlers
GET http://{{host}}:9003/crawlers

###
GET http://{{host}}:9003/crawlers/a32e8672-2e1b-4bed-ad11-48899fa6c41c/status


### GET a crawler
GET http://{{host}}:9003/crawlers/76702747-b70e-4fde-a246-dcfb10879372

### DELETE a crawler
DELETE http://{{host}}:9003/crawlers/{{crawlerId}}

### PUT a crawler's status
PUT http://{{host}}:9003/crawlers/a32e8672-2e1b-4bed-ad11-48899fa6c41c/run

### PUT a crawler's status
PUT http://{{host}}:9003/crawlers/a32e8672-2e1b-4bed-ad11-48899fa6c41c/pause



